include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/firebase_options.dart"
    - "test/**"
    - "integration_test/**"

linter:
  rules:
    # Tests
    test_types_in_equals: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false # Allow print in tests for debugging
