# Configuration de l'environnement de production
# Ce fichier définit les règles de protection pour l'environnement de production

name: production
protection_rules:
  - type: required_reviewers
    required_reviewers: 1
    dismiss_stale_reviews: true
  - type: wait_timer
    wait_timer: 0
  - type: prevent_self_review
    prevent_self_review: true

# Variables d'environnement spécifiques à la production
environment_variables:
  FIREBASE_PROJECT_ID: ecommerceapp-7268d
  DEPLOYMENT_ENVIRONMENT: production

# Secrets requis pour cet environnement
required_secrets:
  - FIREBASE_SERVICE_ACCOUNT_ECOMMERCEAPP_7268D
  - FIREBASE_TOKEN
