// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_ecommerce_app/test/widget/product_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:flutter_ecommerce_app/models/cart.dart' as _i3;
import 'package:flutter_ecommerce_app/models/product.dart' as _i5;
import 'package:flutter_ecommerce_app/providers/cart_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CartProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartProvider extends _i1.Mock implements _i2.CartProvider {
  MockCartProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.CartItem> get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: <_i3.CartItem>[],
          )
          as List<_i3.CartItem>);

  @override
  int get itemCount =>
      (super.noSuchMethod(Invocation.getter(#itemCount), returnValue: 0)
          as int);

  @override
  double get total =>
      (super.noSuchMethod(Invocation.getter(#total), returnValue: 0.0)
          as double);

  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initializeCart() =>
      (super.noSuchMethod(
            Invocation.method(#initializeCart, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addToCart(_i5.Product? product, {int? quantity = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [product], {#quantity: quantity}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromCart(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateQuantity(int? productId, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [productId, quantity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i3.CartItem? getItem(int? productId) =>
      (super.noSuchMethod(Invocation.method(#getItem, [productId]))
          as _i3.CartItem?);

  @override
  bool isInCart(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#isInCart, [productId]),
            returnValue: false,
          )
          as bool);

  @override
  int getQuantity(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuantity, [productId]),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<void> syncWithAPI() =>
      (super.noSuchMethod(
            Invocation.method(#syncWithAPI, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
