name: Tests and Coverage

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate mocks
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run linter
        run: dart analyze

      - name: Run tests
        run: flutter test
